app = "chdum"
primary_region = "sin"

[build]
  image = "python:3.12-slim"

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  processes = ["app"]

  [services.http_checks]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"

  [services.concurrency]
    type = "requests"
    hard_limit = 20
    soft_limit = 10

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
