app = "chdum"
primary_region = "sin"

[build]
  image = "python:3.10"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]

  [services.http_checks]
    interval = "10s"
    timeout = "2s"
    grace_period = "1s"
    method = "get"
    path = "/"
    protocol = "http"

  [services.concurrency]
    hard_limit = 20
    soft_limit = 10
    type = "requests"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
