app = "chdum"
primary_region = "sin"

[build]
  image = "python:3.12-slim"

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80

  [services.http_checks]
    interval = "10s"
    timeout = "2s"
    path = "/"
    method = "get"

  [services.concurrency]
    type = "requests"
    soft_limit = 10
    hard_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
